const STICKER_CLOWN = 'CAADAgADAQADdZiNCIOwAx8aYplWFgQ';
const STICKER_ZHEST = 'CAADAgADAgADdZiNCLY__XALsvwIFgQ';
const STICKER_WASHING = 'CAADAgADUQsAAkxb1gk6ufPChtWMvRYE';

module.exports = {
	STICKER_CLOWN,
	STICKER_ZHEST,
	STICKER_WASHING
};
