module.exports = {
	STICKER_CLOWN: 'CAADAgADAQADdZiNCIOwAx8aYplWFgQ',
	STICKER_ZHEST: 'CAADAgADAgADdZiNCLY__XALsvwIFgQ',
	STICKER_WASHING: 'CAADAgADUQsAAkxb1gk6ufPChtWMvRYE',
	STICKER_STAS: 'CAADAgADJwIAAvNWPxckZQ-UD3LbtRYE',
	STICKER_CLOWN_DETECTED: 'CAACAgIAAxkBAAIpRF5NWrCBicDtbsLX7XLNVoyS8015AAIiAAPNr5AYEDIowYOKZDkYBA'
};
